/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-13 12:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/css/cover.css", Long.valueOf(1723551509550L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>");
      out.write("/* * Globals */\r\n");
      out.write("/* Links */\r\n");
      out.write("a, a:focus, a:hover {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("/* Custom default button */\r\n");
      out.write(".btn-secondary, .btn-secondary:hover, .btn-secondary:focus {\r\n");
      out.write("  color: #333;\r\n");
      out.write("  text-shadow: none;\r\n");
      out.write("  /* Prevent inheritance from `body` */\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border: 0.05rem solid #fff;\r\n");
      out.write("}\r\n");
      out.write("/* * Base structure */\r\n");
      out.write("html, body {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-shadow: 0 0.05rem 0.1rem rgba(0, 0, 0, .5);\r\n");
      out.write("}\r\n");
      out.write("/* Extra markup and styles for table-esque vertical and horizontal centering */\r\n");
      out.write(".site-wrapper {\r\n");
      out.write("  display: table;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  /* For at least Firefox */\r\n");
      out.write("  min-height: 100%;\r\n");
      out.write("  -webkit-box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);\r\n");
      out.write("  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);\r\n");
      out.write("}\r\n");
      out.write(".site-wrapper-inner {\r\n");
      out.write("  display: table-cell;\r\n");
      out.write("  vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".cover-container {\r\n");
      out.write("  margin-right: auto;\r\n");
      out.write("  margin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("/* Padding for spacing */\r\n");
      out.write(".inner {\r\n");
      out.write("  padding: 2rem;\r\n");
      out.write("}\r\n");
      out.write("/* * Header */\r\n");
      out.write(".masthead {\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write(".masthead-brand {\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write(".nav-masthead .nav-link {\r\n");
      out.write("  padding: 0.25rem 0;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: rgba(255, 255, 255, .5);\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  border-bottom: 0.25rem solid transparent;\r\n");
      out.write("}\r\n");
      out.write(".nav-masthead .nav-link:hover, .nav-masthead .nav-link:focus {\r\n");
      out.write("  border-bottom-color: rgba(255, 255, 255, .25);\r\n");
      out.write("}\r\n");
      out.write(".nav-masthead .nav-link + .nav-link {\r\n");
      out.write("  margin-left: 1rem;\r\n");
      out.write("}\r\n");
      out.write(".nav-masthead .active {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  border-bottom-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("@media (min-width: 48em) {\r\n");
      out.write("  .masthead-brand {\r\n");
      out.write("    float: left;\r\n");
      out.write("  }\r\n");
      out.write("  .nav-masthead {\r\n");
      out.write("    float: right;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("/* * Cover */\r\n");
      out.write(".cover {\r\n");
      out.write("  padding: 0 1.5rem;\r\n");
      out.write("}\r\n");
      out.write(".cover .btn-lg {\r\n");
      out.write("  padding: 0.75rem 1.25rem;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("/* * Footer */\r\n");
      out.write(".mastfoot {\r\n");
      out.write("  color: rgba(255, 255, 255, .5);\r\n");
      out.write("}\r\n");
      out.write("/* * Affix and center */\r\n");
      out.write("@media (min-width: 40em) {\r\n");
      out.write("  /* Pull out the header and footer */\r\n");
      out.write("  /* Start the vertical centering */\r\n");
      out.write("  /* Handle the widths */\r\n");
      out.write("  .masthead {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .mastfoot {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .site-wrapper-inner {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("  }\r\n");
      out.write("  .masthead, .mastfoot, .cover-container {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    /* Must be percentage or pixels for horizontal alignment */\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media (min-width: 62em) {\r\n");
      out.write("  .masthead, .mastfoot, .cover-container {\r\n");
      out.write("    width: 42rem;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"WEB-INF/css/cover.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <title>Welcome to Banking</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\" d-flex h-100 text-center text-bg-dark\">\r\n");
      out.write("<div class=\"container text-light\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"d-flex flex-column min-vh-100 justify-content-between\">\r\n");
      out.write("    <nav class=\"navbar nav-masthead navbar-expand\">\r\n");
      out.write("      <div class=\"container-fluid d-flex flex-column flex-sm-row\">\r\n");
      out.write("        <a class=\"navbar-brand link-light fs-2\" href=\"#\"> Banking </a>\r\n");
      out.write("        <div class=\"navbar-nav d-flex gap-3\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link active link-light fw-bold\"> Home </a>\r\n");
      out.write("          <a href=\"#\" class=\"nav-link hover link-secondary fw-bold\"> About  </a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"d-flex flex-column align-items-center gap-3\">\r\n");
      out.write("      <h1 class=\"h1\"> Banking Application </h1>\r\n");
      out.write("      <p class=\"lead text-center\"> Banking application created using JAVA EE, mysql and tomcat server, Designed using Bootstrap, MVC architecture applied. </p>\r\n");
      out.write("      <button class=\"btn btn-light btn-lg\" onclick=\"window.location='login.jsp'\"> SIGN IN </button>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"text-center mb-3 text-secondary\">\r\n");
      out.write("      <div>\r\n");
      out.write("        Application by\r\n");
      out.write("        <span class=\"text-light\"> Devan Khandagale </span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
